using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
namespace CreationEditor.Skyrim;

public static class DialogTopicExtension {
    public static DialogTopic.SubtypeEnum? ToDialogTopicSubtype(this RecordType dialogTopicSubtypeName) {
        return dialogTopicSubtypeName.Type switch {
            "ACAC" => DialogTopic.SubtypeEnum.ActorCollideWithActor,
            "ACYI" => DialogTopic.SubtypeEnum.AcceptYield,
            "AGRE" => DialogTopic.SubtypeEnum.Agree,
            "ALIL" => DialogTopic.SubtypeEnum.AlertIdle,
            "ALKL" => DialogTopic.SubtypeEnum.AllyKilled,
            "ALTC" => DialogTopic.SubtypeEnum.AlertToCombat,
            "ALTN" => DialogTopic.SubtypeEnum.AlertToNormal,
            "ASKF" => DialogTopic.SubtypeEnum.AskFavor,
            "ASKG" => DialogTopic.SubtypeEnum.AskGift,
            "ASNC" => DialogTopic.SubtypeEnum.AssaultNC,
            "ASSA" => DialogTopic.SubtypeEnum.Assault,
            "ATCK" => DialogTopic.SubtypeEnum.Attack,
            "AVTH" => DialogTopic.SubtypeEnum.AvoidThreat,
            "BAEX" => DialogTopic.SubtypeEnum.BarterExit,
            "BASH" => DialogTopic.SubtypeEnum.Bash,
            "BLED" => DialogTopic.SubtypeEnum.Bleedout,
            "BLOC" => DialogTopic.SubtypeEnum.Block,
            "BREA" => DialogTopic.SubtypeEnum.EnterSprintBreath,
            "BRIB" => DialogTopic.SubtypeEnum.Bribe,
            "COLO" => DialogTopic.SubtypeEnum.CombatToLost,
            "COTN" => DialogTopic.SubtypeEnum.CombatToNormal,
            "CUST" => DialogTopic.SubtypeEnum.Custom,
            "DEOB" => DialogTopic.SubtypeEnum.DestroyObject,
            "DETH" => DialogTopic.SubtypeEnum.Death,
            "DFDA" => DialogTopic.SubtypeEnum.DetectFriendDie,
            "ENBZ" => DialogTopic.SubtypeEnum.EnterBowZoomBreath,
            "EXBZ" => DialogTopic.SubtypeEnum.ExitBowZoomBreath,
            "FAVO" => DialogTopic.SubtypeEnum.Favor,
            "FEXT" => DialogTopic.SubtypeEnum.ExitFavorState,
            "FIWE" => DialogTopic.SubtypeEnum.ShootBow,
            "FLAT" => DialogTopic.SubtypeEnum.Flatter,
            "FLEE" => DialogTopic.SubtypeEnum.Flee,
            "FMAT" => DialogTopic.SubtypeEnum.FlyingMountAcceptTarget,
            "FMDR" => DialogTopic.SubtypeEnum.FlyingMountDestinationReached,
            "FMLX" => DialogTopic.SubtypeEnum.FlyingMountLand,
            "FMNT" => DialogTopic.SubtypeEnum.FlyingMountNoTarget,
            "FMRT" => DialogTopic.SubtypeEnum.FlyingMountRejectTarget,
            "FMXL" => DialogTopic.SubtypeEnum.FlyingMountCancelLand,
            "FOLL" => DialogTopic.SubtypeEnum.Follow,
            "FRJT" => DialogTopic.SubtypeEnum.Reject,
            "FVDL" => DialogTopic.SubtypeEnum.Custom,
            "GBYE" => DialogTopic.SubtypeEnum.Goodbye,
            "GIFF" => DialogTopic.SubtypeEnum.Gift,
            "GRNT" => DialogTopic.SubtypeEnum.CombatGrunt,
            "GRST" => DialogTopic.SubtypeEnum.GroupStrategy,
            "HELO" => DialogTopic.SubtypeEnum.Hello,
            "HIT_" => DialogTopic.SubtypeEnum.Hit,
            "IDAT" => DialogTopic.SubtypeEnum.SharedInfo,
            "IDLE" => DialogTopic.SubtypeEnum.Idle,
            "INTI" => DialogTopic.SubtypeEnum.Intimidate,
            "JUMP" => DialogTopic.SubtypeEnum.Jump,
            "KNOO" => DialogTopic.SubtypeEnum.KnockOverObject,
            "LOIL" => DialogTopic.SubtypeEnum.LostIdle,
            "LOOB" => DialogTopic.SubtypeEnum.LockedObject,
            "LOTC" => DialogTopic.SubtypeEnum.LostToCombat,
            "LOTN" => DialogTopic.SubtypeEnum.LostToNormal,
            "LWBS" => DialogTopic.SubtypeEnum.LeaveWaterBreath,
            "MREF" => DialogTopic.SubtypeEnum.MoralRefusal,
            "MUNC" => DialogTopic.SubtypeEnum.MurderNC,
            "MURD" => DialogTopic.SubtypeEnum.Murder,
            "NOTA" => DialogTopic.SubtypeEnum.NormalToAlert,
            "NOTC" => DialogTopic.SubtypeEnum.NormalToCombat,
            "NOTI" => DialogTopic.SubtypeEnum.NoticeCorpse,
            "OBCO" => DialogTopic.SubtypeEnum.ObserveCombat,
            "OUTB" => DialogTopic.SubtypeEnum.OutOfBreath,
            "PCPS" => DialogTopic.SubtypeEnum.PlayerCastProjectileSpell,
            "PCSH" => DialogTopic.SubtypeEnum.PlayerShout,
            "PCSS" => DialogTopic.SubtypeEnum.PlayerCastSelfSpell,
            "PFGT" => DialogTopic.SubtypeEnum.ForceGreet,
            "PICC" => DialogTopic.SubtypeEnum.PickpocketCombat,
            "PICN" => DialogTopic.SubtypeEnum.PickpocketNC,
            "PICT" => DialogTopic.SubtypeEnum.PickpocketTopic,
            "PIRN" => DialogTopic.SubtypeEnum.PlayerInIronSights,
            "POAT" => DialogTopic.SubtypeEnum.PowerAttack,
            "PURS" => DialogTopic.SubtypeEnum.PursueIdleTopic,
            "RCEX" => DialogTopic.SubtypeEnum.RechargeExit,
            "RECH" => DialogTopic.SubtypeEnum.Recharge,
            "REEX" => DialogTopic.SubtypeEnum.RepairExit,
            "REFU" => DialogTopic.SubtypeEnum.Refuse,
            "REPA" => DialogTopic.SubtypeEnum.Repair,
            "RUMO" => DialogTopic.SubtypeEnum.Rumors,
            "SCEN" => DialogTopic.SubtypeEnum.Scene,
            "SERU" => DialogTopic.SubtypeEnum.ServiceRefusal,
            "SHOW" => DialogTopic.SubtypeEnum.Show,
            "SHRE" => DialogTopic.SubtypeEnum.ShowRelationships,
            "STEA" => DialogTopic.SubtypeEnum.Steal,
            "STFN" => DialogTopic.SubtypeEnum.StealFromNC,
            "STOF" => DialogTopic.SubtypeEnum.StandOnFurniture,
            "SWMW" => DialogTopic.SubtypeEnum.SwingMeleeWeapon,
            "TAUT" => DialogTopic.SubtypeEnum.Taunt,
            "TITG" => DialogTopic.SubtypeEnum.TimeToGo,
            "TRAI" => DialogTopic.SubtypeEnum.Training,
            "TRAN" => DialogTopic.SubtypeEnum.TrespassAgainstNC,
            "TRAV" => DialogTopic.SubtypeEnum.Travel,
            "TRES" => DialogTopic.SubtypeEnum.Trespass,
            "TREX" => DialogTopic.SubtypeEnum.TrainingExit,
            "VPEL" => DialogTopic.SubtypeEnum.VoicePowerEndLong,
            "VPES" => DialogTopic.SubtypeEnum.VoicePowerEndShort,
            "VPSL" => DialogTopic.SubtypeEnum.VoicePowerStartLong,
            "VPSS" => DialogTopic.SubtypeEnum.VoicePowerStartShort,
            "WTCR" => DialogTopic.SubtypeEnum.WerewolfTransformCrime,
            "YIEL" => DialogTopic.SubtypeEnum.Yield,
            "ZKEY" => DialogTopic.SubtypeEnum.ZKeyObject,
            _ => null,
        };
    }

    public static bool IsCombatLine(this DialogTopic.SubtypeEnum subtype) {
        return subtype switch {
            DialogTopic.SubtypeEnum.Attack => true,
            DialogTopic.SubtypeEnum.PowerAttack => true,
            DialogTopic.SubtypeEnum.Bash => true,
            DialogTopic.SubtypeEnum.Hit => true,
            DialogTopic.SubtypeEnum.Flee => true,
            DialogTopic.SubtypeEnum.Bleedout => true,
            DialogTopic.SubtypeEnum.Death => true,
            DialogTopic.SubtypeEnum.Block => true,
            DialogTopic.SubtypeEnum.Taunt => true,
            DialogTopic.SubtypeEnum.Steal => true,
            DialogTopic.SubtypeEnum.AcceptYield => true,
            DialogTopic.SubtypeEnum.PickpocketCombat => true,
            DialogTopic.SubtypeEnum.Assault => true,
            DialogTopic.SubtypeEnum.Murder => true,
            DialogTopic.SubtypeEnum.Trespass => true,
            DialogTopic.SubtypeEnum.WerewolfTransformCrime => true,
            DialogTopic.SubtypeEnum.AlertIdle => true,
            DialogTopic.SubtypeEnum.LostIdle => true,
            DialogTopic.SubtypeEnum.NormalToAlert => true,
            DialogTopic.SubtypeEnum.AlertToCombat => true,
            DialogTopic.SubtypeEnum.NormalToCombat => true,
            DialogTopic.SubtypeEnum.CombatToLost => true,
            DialogTopic.SubtypeEnum.LostToCombat => true,
            DialogTopic.SubtypeEnum.DetectFriendDie => true,
            DialogTopic.SubtypeEnum.ObserveCombat => true,
            DialogTopic.SubtypeEnum.NoticeCorpse => true,
            DialogTopic.SubtypeEnum.SwingMeleeWeapon => true,
            DialogTopic.SubtypeEnum.ShootBow => true,
            DialogTopic.SubtypeEnum.PlayerShout => true,
            DialogTopic.SubtypeEnum.KnockOverObject => true,
            DialogTopic.SubtypeEnum.ActorCollideWithActor => true,
            DialogTopic.SubtypeEnum.CombatGrunt => true,
            _ => false,
        };
    }
}
