using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
namespace CreationEditor.Skyrim.Definitions;

public class BoolEnum : IConditionValueEnums {
    private enum TrueFalse { False, True }
    public IList<Enum> Enums { get; set; } = new List<Enum> { TrueFalse.True, TrueFalse.False };

    public bool Match(Condition.Function function) {
        return function
            is Condition.Function.Exists
            or Condition.Function.DoesNotExist
            or Condition.Function.EffectWasDualCast
            or Condition.Function.EPAlchemyEffectHasKeyword
            or Condition.Function.EPAlchemyGetMakingPoison
            or Condition.Function.EPMagic_SpellHasKeyword
            or Condition.Function.EPMagic_SpellHasSkill
            or Condition.Function.EPModSkillUsage_AdvanceObjectHasKeyword
            or Condition.Function.EPModSkillUsage_IsAdvanceAction
            or Condition.Function.EPMagic_IsAdvanceSkill
            or Condition.Function.EPTemperingItemHasKeyword
            or Condition.Function.EPTemperingItemIsEnchanted
            or Condition.Function.GetActorAggroRadiusViolated
            or Condition.Function.GetActorCrimePlayerEnemy
            or Condition.Function.GetAlarmed
            or Condition.Function.GetAllowWorldInteractions
            or Condition.Function.GetArrestedState
            or Condition.Function.GetArrestingActor
            or Condition.Function.GetAttacked
            or Condition.Function.GetCannibal
            or Condition.Function.GetCombatTargetHasKeyword
            or Condition.Function.GetCrime
            or Condition.Function.GetDead
            or Condition.Function.GetDefaultOpen
            or Condition.Function.GetDestroyed
            or Condition.Function.GetDetected
            or Condition.Function.GetDisabled
            or Condition.Function.GetDisease
            or Condition.Function.GetEquipped
            or Condition.Function.GetEquippedShout
            or Condition.Function.GetHasNote
            or Condition.Function.GetIdleDoneOnce
            or Condition.Function.GetIgnoreCrime
            or Condition.Function.GetIgnoreFriendlyHits
            or Condition.Function.GetInCell
            or Condition.Function.GetInCellParam
            or Condition.Function.GetInContainer
            or Condition.Function.GetInCurrentLoc
            or Condition.Function.GetInCurrentLocAlias
            or Condition.Function.GetInCurrentLocFormList
            or Condition.Function.GetInFaction
            or Condition.Function.GetInSameCell
            or Condition.Function.GetInSharedCrimeFaction
            or Condition.Function.GetIntimidateSuccess
            or Condition.Function.GetInWorldspace
            or Condition.Function.GetInZone
            or Condition.Function.GetIsAlerted
            or Condition.Function.GetIsAliasRef
            or Condition.Function.GetIsClass
            or Condition.Function.GetIsClassDefault
            or Condition.Function.GetIsCrashLandRequest
            or Condition.Function.GetIsCrimeFaction
            or Condition.Function.GetIsCurrentPackage
            or Condition.Function.GetIsCurrentWeather
            or Condition.Function.GetIsEditorLocAlias
            or Condition.Function.GetIsEditorLocation
            or Condition.Function.GetIsFlying
            or Condition.Function.GetIsGhost
            or Condition.Function.GetIsHastyLandRequest
            or Condition.Function.GetIsID
            or Condition.Function.GetIsInjured
            or Condition.Function.GetIsObjectType
            or Condition.Function.GetIsPlayableRace
            or Condition.Function.GetIsRace
            or Condition.Function.GetIsReference
            or Condition.Function.GetIsSex
            or Condition.Function.GetIsUsedItemEquipType
            or Condition.Function.GetIsVoiceType
            or Condition.Function.GetKnockedState
            or Condition.Function.GetLastHitCritical
            or Condition.Function.GetLineOfSight
            or Condition.Function.GetLocationAliasCleared
            or Condition.Function.GetLocationCleared
            or Condition.Function.GetLocked
            or Condition.Function.GetMapMarkerVisible
            or Condition.Function.GetNoBleedoutRecovery
            or Condition.Function.GetOffersServicesNow
            or Condition.Function.GetPairedAnimation
            or Condition.Function.GetPCEnemyofFaction
            or Condition.Function.GetPCExpelled
            or Condition.Function.GetPCFactionAttack
            or Condition.Function.GetPCFactionMurder
            or Condition.Function.GetPCInFaction
            or Condition.Function.GetPCIsClass
            or Condition.Function.GetPCIsRace
            or Condition.Function.GetPCIsSex
            or Condition.Function.GetPlayerTeammate
            or Condition.Function.GetQuestCompleted
            or Condition.Function.GetQuestRunning
            or Condition.Function.GetRestrained
            or Condition.Function.GetShouldAttack
            or Condition.Function.GetShouldHelp
            or Condition.Function.GetStageDone
            or Condition.Function.GetTalkedToPC
            or Condition.Function.GetTalkedToPCParam
            or Condition.Function.GetUnconscious
            or Condition.Function.GetVampireFeed
            or Condition.Function.GetVATSBackAreaFree
            or Condition.Function.GetVATSBackTargetVisible
            or Condition.Function.GetVATSFrontAreaFree
            or Condition.Function.GetVATSFrontTargetVisible
            or Condition.Function.GetVATSLeftAreaFree
            or Condition.Function.GetVATSLeftTargetVisible
            or Condition.Function.GetVATSRightAreaFree
            or Condition.Function.GetVATSRightTargetVisible
            or Condition.Function.GetWantBlocking
            or Condition.Function.GetWithinDistance
            or Condition.Function.GetWithinPackageLocation
            or Condition.Function.HasAssociationType
            or Condition.Function.HasAssociationTypeAny
            or Condition.Function.HasBeenEaten
            or Condition.Function.HasBoundWeaponEquipped
            or Condition.Function.HasEquippedSpell
            or Condition.Function.HasFamilyRelationship
            or Condition.Function.HasFamilyRelationshipAny
            or Condition.Function.HasKeyword
            or Condition.Function.HasLinkedRef
            or Condition.Function.HasLoaded3D
            or Condition.Function.HasMagicEffect
            or Condition.Function.HasMagicEffectKeyword
            or Condition.Function.HasParentRelationship
            or Condition.Function.HasPerk
            or Condition.Function.HasRefType
            or Condition.Function.HasSameEditorLocAsRef
            or Condition.Function.HasSameEditorLocAsRefAlias
            or Condition.Function.HasShout
            or Condition.Function.HasSpell
            or Condition.Function.HasTwoHandedWeaponEquipped
            or Condition.Function.IsActor
            or Condition.Function.IsActorAVictim
            or Condition.Function.IsActorUsingATorch
            or Condition.Function.IsAllowedToFly
            or Condition.Function.IsAttacking
            or Condition.Function.IsAttackType
            or Condition.Function.IsBeingRidden
            or Condition.Function.IsBleedingOut
            or Condition.Function.IsBribedbyPlayer
            or Condition.Function.IsCarryable
            or Condition.Function.IsCasting
            or Condition.Function.IsCellOwner
            or Condition.Function.IsChild
            or Condition.Function.IsCloserToAThanB
            or Condition.Function.IsCloudy
            or Condition.Function.IsCombatTarget
            or Condition.Function.IsCommandedActor
            or Condition.Function.IsContinuingPackagePCNear
            or Condition.Function.IsCurrentFurnitureObj
            or Condition.Function.IsCurrentFurnitureRef
            or Condition.Function.IsCurrentSpell
            or Condition.Function.IsDualCasting
            or Condition.Function.IsEnteringInteractionQuick
            or Condition.Function.IsEssential
            or Condition.Function.IsExitingInstant
            or Condition.Function.IsExitingInteractionQuick
            or Condition.Function.IsFacingUp
            or Condition.Function.IsFleeing
            or Condition.Function.IsFlyingMountFastTravelling
            or Condition.Function.IsFlyingMountPatrolQueud
            or Condition.Function.IsFurnitureAnimType
            or Condition.Function.IsFurnitureEntryType
            or Condition.Function.IsGoreDisabled
            or Condition.Function.IsGreetingPlayer
            or Condition.Function.IsGuard
            or Condition.Function.IsHostileToActor
            or Condition.Function.IsIgnoringCombat
            or Condition.Function.IsInCombat
            or Condition.Function.IsInCriticalStage
            or Condition.Function.IsInDangerousWater
            or Condition.Function.IsInDialogueWithPlayer
            or Condition.Function.IsInFavorState
            or Condition.Function.IsInFriendStateWithPlayer
            or Condition.Function.IsInFurnitureState
            or Condition.Function.IsInInterior
            or Condition.Function.IsInList
            or Condition.Function.IsInMyOwnedCell
            or Condition.Function.IsInSameCurrentLocAsRef
            or Condition.Function.IsInSameCurrentLocAsRefAlias
            or Condition.Function.IsInScene
            or Condition.Function.IsIntimidatedbyPlayer
            or Condition.Function.IsKiller
            or Condition.Function.IsKillerObject
            or Condition.Function.IsLastHostileActor
            or Condition.Function.IsLastIdlePlayed
            or Condition.Function.IsLeftUp
            or Condition.Function.IsLimbGone
            or Condition.Function.IsLinkedTo
            or Condition.Function.IsLocAliasLoaded
            or Condition.Function.IsLocationLoaded
            or Condition.Function.IsNullPackageData
            or Condition.Function.IsOnFlyingMount
            or Condition.Function.IsOwner
            or Condition.Function.IsPathing
            or Condition.Function.IsPC1stPerson
            or Condition.Function.IsPCAMurderer
            or Condition.Function.IsPCSleeping
            or Condition.Function.IsPlayerActionActive
            or Condition.Function.IsPlayerGrabbedRef
            or Condition.Function.IsPlayerInRegion
            or Condition.Function.IsPlayerMovingIntoNewSpace
            or Condition.Function.IsPlayersLastRiddenMount
            or Condition.Function.IsPleasant
            or Condition.Function.IsPoison
            or Condition.Function.IsPowerAttacking
            or Condition.Function.IsProtected
            or Condition.Function.IsRaining
            or Condition.Function.IsRecoiling
            or Condition.Function.IsRidingMount
            or Condition.Function.IsRotating
            or Condition.Function.IsRunning
            or Condition.Function.IsSceneActionComplete
            or Condition.Function.IsScenePackageRunning
            or Condition.Function.IsScenePlaying
            or Condition.Function.IsShieldOut
            or Condition.Function.IsSmallBump
            or Condition.Function.IsSneaking
            or Condition.Function.IsSnowing
            or Condition.Function.IsSpellTarget
            or Condition.Function.IsSprinting
            or Condition.Function.IsStaggered
            or Condition.Function.IsSwimming
            or Condition.Function.IsTalking
            or Condition.Function.IsTalkingActivatorActor
            or Condition.Function.IsTimePassing
            or Condition.Function.IsTorchOut
            or Condition.Function.IsTrespassing
            or Condition.Function.IsTurning
            or Condition.Function.IsUndead
            or Condition.Function.IsUnique
            or Condition.Function.IsUnlockedDoor
            or Condition.Function.IsWardState
            or Condition.Function.IsWarningAbout
            or Condition.Function.IsWaterObject
            or Condition.Function.IsWeaponInList
            or Condition.Function.IsWeaponMagicOut
            or Condition.Function.IsWeaponSkillType
            or Condition.Function.LocAliasHasKeyword
            or Condition.Function.LocAliasIsLocation
            or Condition.Function.LocationHasKeyword
            or Condition.Function.LocationHasRefType
            or Condition.Function.PlayerKnows
            or Condition.Function.SameFaction
            or Condition.Function.SameFactionAsPC
            or Condition.Function.SameRace
            or Condition.Function.SameRaceAsPC
            or Condition.Function.SameSex
            or Condition.Function.SameSexAsPC
            or Condition.Function.ShouldAttackKill
            or Condition.Function.SpellHasCastingPerk
            or Condition.Function.SpellHasKeyword
            or Condition.Function.WornHasKeyword;
    }
}
